backend:
  name: test-repo
  login: false
media_folder: assets
collections:
  - label: Test
    name: test
    files:
      - file: test.yml
        name: test
        label: Test
        fields:
          - name: ai_chat
            label: Assistant
            widget: ai-chat
            owner: dinosoeren
            repo: walls.dev
